package com.speedystone.greendaodemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import xyz.wendyltanpcy.formulaapplication.Model.Formula;
import xyz.wendyltanpcy.formulaapplication.Model.YValue;

import com.speedystone.greendaodemo.db.FormulaDao;
import com.speedystone.greendaodemo.db.YValueDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig formulaDaoConfig;
    private final DaoConfig yValueDaoConfig;

    private final FormulaDao formulaDao;
    private final YValueDao yValueDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        formulaDaoConfig = daoConfigMap.get(FormulaDao.class).clone();
        formulaDaoConfig.initIdentityScope(type);

        yValueDaoConfig = daoConfigMap.get(YValueDao.class).clone();
        yValueDaoConfig.initIdentityScope(type);

        formulaDao = new FormulaDao(formulaDaoConfig, this);
        yValueDao = new YValueDao(yValueDaoConfig, this);

        registerDao(Formula.class, formulaDao);
        registerDao(YValue.class, yValueDao);
    }
    
    public void clear() {
        formulaDaoConfig.clearIdentityScope();
        yValueDaoConfig.clearIdentityScope();
    }

    public FormulaDao getFormulaDao() {
        return formulaDao;
    }

    public YValueDao getYValueDao() {
        return yValueDao;
    }

}
