package com.speedystone.greendaodemo.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import xyz.wendyltanpcy.formulaapplication.Model.YValue;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "YVALUE".
*/
public class YValueDao extends AbstractDao<YValue, Long> {

    public static final String TABLENAME = "YVALUE";

    /**
     * Properties of entity YValue.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Y = new Property(0, double.class, "y", false, "Y");
        public final static Property Id = new Property(1, long.class, "id", true, "_id");
    }


    public YValueDao(DaoConfig config) {
        super(config);
    }
    
    public YValueDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"YVALUE\" (" + //
                "\"Y\" REAL NOT NULL ," + // 0: y
                "\"_id\" INTEGER PRIMARY KEY NOT NULL );"); // 1: id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"YVALUE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, YValue entity) {
        stmt.clearBindings();
        stmt.bindDouble(1, entity.getY());
        stmt.bindLong(2, entity.getId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, YValue entity) {
        stmt.clearBindings();
        stmt.bindDouble(1, entity.getY());
        stmt.bindLong(2, entity.getId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 1);
    }    

    @Override
    public YValue readEntity(Cursor cursor, int offset) {
        YValue entity = new YValue( //
            cursor.getDouble(offset + 0), // y
            cursor.getLong(offset + 1) // id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, YValue entity, int offset) {
        entity.setY(cursor.getDouble(offset + 0));
        entity.setId(cursor.getLong(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(YValue entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(YValue entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(YValue entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
